#!/bin/bash
#### version-info.sh ####
export GIT_COMMIT=COMMIT-REPLACE
export GIT_TAG=TAG-REPLACE
export GIT_MOST_RECENT_TAG=VERSION-REPLACE
export BUILD_MACHINE="HOSTNAME-REPLACE"
export BUILD_DATE="TIMESTAMP-REPLACE"
